version: '3.4'

networks:
  budgetBuddyNetwork:

services:
  budgetbuddydb:
    container_name: budgetbuddy-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
        - 8004:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345
      - MSSQL_PID=Express
    networks:
      - budgetBuddyNetwork
  budgetbuddyapi:
    container_name: budgetbuddy-app
    image: ${DOCKER_REGISTRY-}budgetbuddyapi
    build:
      context: .
      dockerfile: BudgetBuddyAPI/Dockerfile
    ports:
      - 8003:80
    depends_on:
      - budgetbuddydb
    networks:
      - budgetBuddyNetwork
  budgetbuddyclient:
    container_name: budgetbuddy-frontend
    build:
      context:  C:/workspace/ALX/AlxProject/BudgetBuddy/BudgetBuddy_front-end/budget-buddy_client  # Assuming your frontend directory is named "frontend"
      dockerfile: Dockerfile
    ports:
      - 3000:3000  # Expose the frontend on port 3000
    networks:
      - budgetBuddyNetwork